<a href="https://colab.research.google.com/github/luxlox/PyBasico/blob/main/Basico_Py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Somar 2 números**

In [ ]:
a = 10
b = 20
soma = a + b
print("Soma:", soma)

Soma: 30


# Verificar **idade**

In [ ]:
idade = 17
if idade <=18:
  print("menor de idade")
else:
  print("maior de idade")


menor de idade


# **Contar Letras**

In [ ]:
texto = "Python"
print(len(texto))

6


# **Soma de uma lista sem SUM**

In [ ]:
lista = [1, 5, 7, 2]
soma = 0
for num in lista:
  soma += num
print ("Soma:", soma)


Soma: 15


# **Maior número de uma lista**

In [ ]:
lista = [10, 25, 3, 99,18]
maior = lista[0]
for num in lista:
  if num > maior:
    maior = num

print ("Maior número da lista:", maior)

Maior número da lista: 99


# **Contar quantas vezes aparece o número 3**

In [ ]:
lista = [3, 2, 3, 1, 5, 3]
contador = 0
for num in lista:
  if num == 3:
    contador += 1

print ("Quantidade de 3:", contador)

Quantidade de 3: 3


# **Filtrar números pares**

In [ ]:
lista = [1, 2, 3, 4, 5, 6]
pares = []
for num in lista:
  if num % 2 == 0:
    pares.append(num)

print("Pares:", pares)


Pares: [2, 4, 6]


# **Média de notas + aprovado/reprovado**

In [ ]:
notas = [8, 7, 6, 9]
soma = 0

for n in notas:
    soma += n

media = soma / len(notas)

print("Média:", media)

if media >= 7:
    print("Aprovado!")
else:
    print("Reprovado!")


Média: 7.5
Aprovado!


# **Função que soma uma lista**

In [ ]:
def soma_lista(lista):
    soma = 0
    for num in lista:
        soma += num
    return soma

print(soma_lista([1,2,3,4]))


10


# **Função que verifica palíndromo**

In [ ]:
def palindromo(palavra):
    palavra = palavra.lower()
    return palavra == palavra[::-1]

print(palindromo("arara"))
print(palindromo("casa"))


True
False


# **Caixa eletrônico (notas 100, 50, 10 e 1)**

In [ ]:
valor = 287

n100 = valor // 100
resto = valor % 100

n50 = resto // 50
resto = resto % 50

n10 = resto // 10
resto = resto % 10

n1 = resto

print("100:", n100)
print("50:", n50)
print("10:", n10)
print("1 :", n1)


100: 2
50: 1
10: 3
1 : 7


# **Jogo: adivinhe o número**

In [ ]:
import random

segredo = random.randint(1, 10)
tentativa = 0

while tentativa != segredo:
    tentativa = int(input("Adivinhe (1 a 10): "))
    if tentativa != segredo:
        print("Errou! Tente de novo.")

print("Acertou!")


# **Lista de pessoas (nome + idade)**

In [ ]:
pessoas = []

for i in range(5):
    nome = input("Nome: ")
    idade = int(input("Idade: "))
    pessoas.append([nome, idade])

print("\nTabela:")
for pessoa in pessoas:
    print("Nome:", pessoa[0], "| Idade:", pessoa[1])




# **NUMPY**



In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a)
type(a)


lista = [1, 2, 3]
array = np.array([1, 2, 3])
print("Lista *2:" lista * 2)
print("Array *2:"array * 2)





[1 2 3]
[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
print("a[0] =>", a[0])
print("a[3] ->", a[3])

#SLICES

print("a[0:3] =>", a[0:3])
print("a[2:] => ", a[2:])
print("a[:3] => ", a[:3])

m = np.array([[1, 2, 3],[4, 5, 6]])

print(m)
print("m[0,0] => ", m[0,0])
print("m[1,2] => ", m[1,2])
print("m[0][2] =>", m[0][2])

print("m Shape =>", m.shape)
print("a Shape =>", a.shape)

print("Matriz cheia de zeros: ", np.zeros((3,4)))

print("Matriz cheia de uns:", np.ones((2,3)))

print("Intervalo automático: ", np.arange(0, 10, 2))

print("Espaçamento uniforme:", np.linspace(0,1,5))






a[0] => 10
a[3] -> 40
a[0:3] => [10 20 30]
a[2:] =>  [30 40]
a[:3] =>  [10 20 30]
[[1 2 3]
 [4 5 6]]
m[0,0] =>  1
m[1,2] =>  6
m[0][2] => 3
m Shape => (2, 3)
a Shape => (4,)
Matriz cheia de zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matriz cheia de uns: [[1. 1. 1.]
 [1. 1. 1.]]
Intervalo automático:  [0 2 4 6 8]
Espaçamento uniforme: [0.   0.25 0.5  0.75 1.  ]


# **NUMPY - Operações Matemáticas com Arrays**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = a + 10
print(b)     # [11 12 13]


[11 12 13]


In [ ]:
a = np.array([1, 2, 3])
b = a * 2
print(b)     # [2 4 6]


[2 4 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)   # [11 22 33]
print(a * b)   # [10 40 90]


[11 22 33]
[10 40 90]


In [ ]:
a = np.array([1, 4, 9])

print(np.sqrt(a))    # raiz → [1 2 3]
print(np.log(a))     # logaritmo
print(np.exp(a))     # exponencial


[1. 2. 3.]
[0.         1.38629436 2.19722458]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [ ]:
a = np.array([10, 20, 30, 40])

print(a.mean())   # média
print(a.sum())    # soma
print(a.min())    # menor valor
print(a.max())    # maior valor
print(a.std())    # desvio padrão


25.0
100
10
40
11.180339887498949


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = a + 10
print(b)     # [11 12 13]


m = np.array([ [1, 2, 3], [4, 5, 6] ])
print(m.sum(axis=0)) # [5 7 9]
print(m.sum(axis=1)) # [6 15]



[11 12 13]
[5 7 9]
[ 6 15]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(a)
print(b)

c = a.reshape(3, 2)
print(c)

d = a.reshape(6, 1)
print(d)

e = a.reshape(1, 6)
print(e)

f = a.reshape(2, -1)
print(f)




[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


m[linhas, colunas]

:     → tudo

a:b   → do índice a até b-1

::k   → de k em k (passo)


In [ ]:
import numpy as np
m = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print("m[:, 2]", m[:, 2])
print("m[0:2, :]", m[0:2, :])

m[:, 2] [30 60 90]
m[0:2, :] [[10 20 30]
 [40 50 60]]


# **Broadcasting**

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
resultado = a+10
print(resultado)

m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
v = np.array([10, 20, 30])
resultado1 = m + v
print(resultado1)






[11 12 13]
[[11 22 33]
 [14 25 36]]


# **Estatísticas no NumPy**

In [ ]:
import numpy as np

# Criando um array de exemplo
dados = np.array([10, 20, 30, 40, 50])

print("Dados:", dados)

# --- Estatísticas básicas ---
media = np.mean(dados)
mediana = np.median(dados)
desvio = np.std(dados)
variancia = np.var(dados)
minimo = np.min(dados)
maximo = np.max(dados)

print("\n--- Estatísticas ---")
print("Média:", media)
print("Mediana:", mediana)
print("Desvio Padrão:", desvio)
print("Variância:", variancia)
print("Valor mínimo:", minimo)
print("Valor máximo:", maximo)

# --- Estatísticas por linha e coluna ---
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("\nMatriz:")
print(matriz)

print("\nMédia por coluna (axis=0):", np.mean(matriz, axis=0))
print("Média por linha  (axis=1):", np.mean(matriz, axis=1))

print("\nSoma por coluna (axis=0):", matriz.sum(axis=0))
print("Soma por linha  (axis=1):", matriz.sum(axis=1))


Dados: [10 20 30 40 50]

--- Estatísticas ---
Média: 30.0
Mediana: 30.0
Desvio Padrão: 14.142135623730951
Variância: 200.0
Valor mínimo: 10
Valor máximo: 50

Matriz:
[[1 2 3]
 [4 5 6]]

Média por coluna (axis=0): [2.5 3.5 4.5]
Média por linha  (axis=1): [2. 5.]

Soma por coluna (axis=0): [5 7 9]
Soma por linha  (axis=1): [ 6 15]
